//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Cub.View
{
    public class CharController
    {
        public string Name;
		public System.Guid Id;
        public Cub.Class Class;
        public Vector2 Location;
        public string Team;

		public CharController(string name, System.Guid id, Cub.Class cl, Vector2 loc, string team)
        {
            Name = name;
            Id = id;
            Class = cl;
            Location = loc;
            Team = team;
        }


    }
}

