//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace Cub.View
{
    public class Eventon
    {
        public Cub.Event Type;
        public string Description;
        public List<object> Data;
        public bool MainAction;

        public Eventon(Cub.Event type, string desc, bool ma, List<object> data)
        {
            Type = type;
            Description = desc;
            Data = data;
            MainAction = ma;
        }

    }
}

