//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AM;
using UnityEngine;


namespace AM
{
public class CharController
{
		public string Name;
		public string UniqueName;
		public Cub.Type.Class Class;
		public Vector2 Location;
	
		public CharController (string name,string uname, Cub.Type.Class cl, Vector2 loc)
		{
			Name = name;
			UniqueName = uname;
			Class = cl;
			Location = loc;	
		}


}
}

