//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;


namespace AM
{
public class GameEvent
{
		public Cub.Type.GEventType Type;
		public List<string> Data;
//		public ClassController MainChar;
//		public Vector2 Where1;
		//public Vector2 Where2;

		public GameEvent (Cub.Type.GEventType type, List<string> data)
		{
			Type = type;
			Data = data;
			//MainChar = mainChar;
		}

//		public GameEvent (GEventType type, ClassController mainChar, Vector2 where1)
//		{
//			Type = type;
//			MainChar = mainChar;
//			Where1 = where1;
//			//Where2 = where2;
//		}

}
}

