//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AM
{
//	public enum TTerrain
//	{
//		Grass = 1,
//		Desert = 2
//	}
//
//	public enum CharClass
//	{
//		Knight,
//		Archer,
//		Mage
//	}
//
//	public enum Actions
//	{
//		Walk,
//		Attack,
//		TakeDamage,
//		Die
//	}
//
}

